version: '3.4'

services:

  otel-collector:   
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.42.0
    command: ["--config=/etc/otel-collector-config.yaml"]

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest

  tempo:
    container_name: tempo
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]

  loki:
    container_name: loki
    image: grafana/loki:latest
    command: [ "-config.file=/etc/loki/local-config.yaml" ]

  grafana:
    container_name: grafana
    image: grafana/grafana:8.3.3
    depends_on:
      - prometheus
      - tempo
      - loki

  postgresql:    
    container_name: postgresql
    image: postgres:alpine

  rabbitmq:
    container_name: rabbitmq
    image: masstransit/rabbitmq

  sample.cli:
    container_name: sample-cli
    image: ${DOCKER_REGISTRY-}samplecli
    build:
      context: .
      dockerfile: src/Zamat.Sample.Cli/Dockerfile
    depends_on:
      - postgresql

  sample.apigateway:
    container_name: sample-apigateway
    image: ${DOCKER_REGISTRY-}sampleapigateway
    build:
      context: .
      dockerfile: src/Zamat.Sample.ApiGateway/Dockerfile

  users.api.rest:
    container_name: users-api-rest
    image: ${DOCKER_REGISTRY-}usersapirest
    build:
      context: .
      dockerfile: src/Zamat.Sample.Services.Users.Api.Rest/Dockerfile
    depends_on:
      - sample.cli
      - rabbitmq

  audit.event.listener:
    container_name: audit-event-listener
    image: ${DOCKER_REGISTRY-}auditeventlistener
    build:
      context: .
      dockerfile: src/Zamat.Sample.Services.Audit.EventListener/Dockerfile
    depends_on:
      - sample.cli
      - rabbitmq

