version: '3.4'

services:

  postgresql:    
    container_name: postgresql
    image: postgres:alpine

  rabbitmq:
    container_name: rabbitmq
    image: masstransit/rabbitmq

  sample.cli:
    container_name: sample-cli
    image: ${DOCKER_REGISTRY-}samplecli
    build:
      context: .
      dockerfile: src/Zamat.Sample.Cli/Dockerfile
    depends_on:
      - postgresql

  sample.apigateway:
    container_name: sample-apigateway
    image: ${DOCKER_REGISTRY-}sampleapigateway
    build:
      context: .
      dockerfile: src/Zamat.Sample.ApiGateway/Dockerfile

  users.api.rest:
    container_name: users-api-rest
    image: ${DOCKER_REGISTRY-}usersapirest
    build:
      context: .
      dockerfile: src/Zamat.Sample.Services.Users.Api.Rest/Dockerfile
    depends_on:
      - sample.cli
      - rabbitmq

