version: '3.4'

services:

  otel-collector:   
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.42.0
    command: ["--config=/etc/otel-collector-config.yaml"]

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest

  tempo:
    container_name: tempo
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]

  loki:
    container_name: loki
    image: grafana/loki:latest
    command: [ "-config.file=/etc/loki/local-config.yaml" ]

  grafana:
    container_name: grafana
    image: grafana/grafana:8.3.3
    depends_on:
      - prometheus
      - tempo
      - loki

  postgresql:    
    container_name: postgresql
    image: postgres:alpine

  rabbitmq:
    container_name: rabbitmq
    image: masstransit/rabbitmq

  sample.cli:
    container_name: sample-cli
    image: ${DOCKER_REGISTRY-}samplecli
    build:
      context: ../../
      dockerfile: ./src/Zamat.Clean.Cli/Dockerfile
    depends_on:
      - postgresql

  sample.apigateway:
    container_name: sample-apigateway
    image: ${DOCKER_REGISTRY-}sampleapigateway
    build:
      context: ../../
      dockerfile: src/Zamat.Clean.ApiGateway/Dockerfile

  users.api.rest:
    container_name: users-api-rest
    image: ${DOCKER_REGISTRY-}usersapirest
    build:
      context: ../../
      dockerfile: src/Zamat.Clean.Services.Users.Api.Rest/Dockerfile
    depends_on:
      - sample.cli
      - rabbitmq

  users.api.grpc:
    container_name: users-api-grpc
    image: ${DOCKER_REGISTRY-}usersapigrpc
    build:
      context: ../../
      dockerfile: src/Zamat.Clean.Services.Users.Api.Grpc/Dockerfile
    depends_on:
      - sample.cli
      - rabbitmq

  content.api.rest:
    container_name: content-api-rest
    image: ${DOCKER_REGISTRY-}contentapirest
    build:
      context: ../../
      dockerfile: src/Zamat.Clean.Services.Content.Api.Rest/Dockerfile
    depends_on:
      - sample.cli

  audit.worker:
    container_name: audit-worker
    image: ${DOCKER_REGISTRY-}auditworker
    build:
      context: ../../
      dockerfile: src/Zamat.Clean.Services.Audit.Worker/Dockerfile
    depends_on:
      - sample.cli
      - rabbitmq

