version: '3.4'

services:

  otel-collector:   
    ports:
      - "1888:1888"
      - "8888:8888"
      - "8889:8889"
      - "14250:14250"
      - "13133:13133"
      - "4317:4317"
      - "55679:55679"
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml

  prometheus:
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml

  tempo:
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml

  grafana:
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml

  postgresql:    
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
      - "5433:5432"

  rabbitmq:
    ports:
      - 15672:15672
      - 5672:5672

  sample.cli:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SQLCONNSTR_UsersDbContext=postgreSQL://Host=postgresql;Database=SampleDb;Username=postgres;Password=postgres;

  sample.apigateway:
    extra_hosts:
       - "host.docker.internal:host-gateway"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/aspnetapp.key
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.crt
      - OpenTelemetryServiceOptions__OtlpEndpoint=http://otel-collector:4317
    ports:
      - "8080:80"
      - "8090:443"
    volumes:
      - ~/.aspnet/https:/https:ro
      - type: bind
        source: ./Ocelot
        target: /app/Ocelot

  users.api.rest:
    extra_hosts:
       - "host.docker.internal:host-gateway"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/aspnetapp.key
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.crt
      - SQLCONNSTR_UsersDbContext=postgreSQL://Host=postgresql;Database=SampleDb;Username=postgres;Password=postgres;
      - ConnectionStrings__RabbitMQ=amqp://guest:guest@rabbitmq:5672 
      - OpenTelemetryServiceOptions__OtlpEndpoint=http://otel-collector:4317
    ports:
      - "8081:80"
      - "8091:443"
    volumes:
      - ~/.aspnet/https:/https:ro